l_portuguese:
  EDITOR_SETTINGS: "Configurações do editor"
  PERFORMANCE: "Desempenho"
  SPACE: "Espaço"
  SPACES: "Espaços"
  TAB: "Aba"
  TABS: "Abas"
  EXTERNAL_EDITOR: "Editor externo"
  EXTERNAL_EDITOR_DESC: "O editor externo que será usado ao clicar no botão de edição."
  SELECT_PROGRAM: "Selecione o programa editor"
  INDENTATION: "Indentação"
  INDENTATION_DESC: "Caracteres de indentação que serão usados ao usar o editor externo e visualizar dicas de ferramentas"
  PAGE_SIZE: "Tamanho da página"
  PAGE_SIZE_DESC: "A quantidade de nós que serão exibidos por página.\nQuanto mais nós forem exibidos, mais tempo levará para carregar novos nódulos"
  MAX_TOOLTIP_LINES: "Máximo de linhas de dicas de ferramenta"
  MAX_TOOLTIP_LINES_DESC: "O máximo de linhas de dicas de ferramentas de visualização de nós."
  ENABLE_NODE_TAGS: "Habilitar tags de nó"
  ENABLE_NODE_TAGS_DESC: "As tags de nó diminuem o desempenho, pois cada 
nó tem que ser analisado para determinar uma tag de nó a ser exibida."
  ENABLE_NODE_JUMPS: "Habilitar saltos de nós"
  ENABLE_NODE_JUMPS_DESC: "Os saltos de nós diminuem o desempenho, pois cada nó precisa ser analisado para determinar onde saltar."
  WARN_ON_TYPE_CHANGE: "Avisar sobre mudança de tipo"
  WARN_ON_TYPE_CHANGE_DESC: "Exibir um aviso ao alterar o tipo de dados de uma entrada, pois isso geralmente não é intencional."
  EXTERNAL_EDITOR_WAIT_INTERVAL: "Período de espera de recarga do editor externo (ms)"
  EXTERNAL_EDITOR_WAIT_INTERVAL_DESC: "Ao salvar um arquivo editado usando um editor externo, o editor do Pdx-Unlimiter aguarda o tempo especificado até ler o arquivo. Isso pode ser útil para evitar erros causados pela leitura do arquivo muito cedo, caso você esteja usando um disco rígido lento."