l_spanish:
  EDITOR_SETTINGS: "Editor settings"
  PERFORMANCE: "Rendimiento"
  SPACE: "espacio"
  SPACES: "espacios"
  TAB: "tab"
  TABS: "tabs"
  EXTERNAL_EDITOR: "Editor externo"
  EXTERNAL_EDITOR_DESC: "Editor externo que se usará al hacer click en el boton de editar."
  SELECT_PROGRAM: "Seleccionar programa editor"
  INDENTATION: "Indentación"
  INDENTATION_DESC: "Caracteres de indentación que se usarán en el editor externo y para previews de herramientas."
  PAGE_SIZE: "Tamaño de página"
  PAGE_SIZE_DESC: "Cantidad de nodos que se muestran por página.\nCuantos más nodos, más tiempo tardará en cargar."
  MAX_TOOLTIP_LINES: "Max lineas de preview"
  MAX_TOOLTIP_LINES_DESC: "El máximo de lineas que se mostrarán en las previews de las herramientas de nodos."
  ENABLE_NODE_TAGS: "Habilitar etiquetas de nodos"
  ENABLE_NODE_TAGS_DESC: "Las etiquetas de nodo disminuyen el rendimiento ya que cada nodo debe analizarse para determinar qué etiqueta de nodo mostrar."
  ENABLE_NODE_JUMPS: "Habilitar saltos de nodo"
  ENABLE_NODE_JUMPS_DESC: "Las etiquetas de nodo disminuyen el rendimiento ya que cada nodo debe analizarse para determinar donde saltar."
  WARN_ON_TYPE_CHANGE: "Avisar al cambiar tipo de dato"
  WARN_ON_TYPE_CHANGE_DESC: "Mostrar una advertencia al cambiar el tipo de datos de una entrada, ya que esto generalmente no es intencionado."
  EXTERNAL_EDITOR_WAIT_INTERVAL: "Interválo de espera para recargar editor externo (ms)"
  EXTERNAL_EDITOR_WAIT_INTERVAL_DESC: "Al guardar un archivo editado usando un editor externo, el editor Pdx-Unlimiter espera la cantidad de tiempo especificada hasta leer el archivo. Esto puede resultar útil para evitar errores causados por leer el archivo demasiado pronto en caso de que esté utilizando un disco duro lento."