l_spanish:
 SETTINGS: "Configuración"
 INTERFACE: "Interfaz"
 GENERAL: "General"
 IMPORTS: "Importaciones"
 IRONY: "Irony mod manager"
 USE_GAME_LANGUAGE: "Usar idioma del juego"
 MAX_TOOLTIP_SIZE: "Ancho máximo de herramientas"
 MAX_TOOLTIP_SIZE_DESC: "El ancho máximo de previews de las herramientas de nodos en píxeles."
 USE_GAME_LANGUAGE_DESC: "Usa siempre el idioma seleccionado del juego.\nSi está habilitado, la configuración de idioma personalizada a continuación no se usará. ¡Las traducciones están incompletas!"
 LANGUAGE: "Idioma"
 LANGUAGE_DESC: "Idioma de la interfaz.\Solo se aplica si 'Usar idioma del juego' no se selecciona."
 SELECT_DIR: "Seleccionar directorio $DIR$"
 CHOICE_VALUE_ERROR: "Valor $VAL$ es invalido. Restableciendo a el valor default"
 GAME_DIRS: "Rutas de juegos"
 GAME_DIR_ERROR: "Ocurrió un error al cargar tu instalación de $GAME$"
 GAME_DIR_ERROR_MSG: "El soporte de $GAME$ ha sido deshabilitado. Si crees que tu instalación es válida,\npor favor verifica si la ruta de instalación es correcta."
 GAME_DIR: "Ruta de $GAME$"
 GAME_DIR_DESC: "Ruta de $GAME$.\n\nTen en cuenta que esta ruta debe de contener los ejecutables y assets del juego\nNO uses la ruta usuario que contiene tus partidas guardadas y mods."
 STORAGE_DIR: "Storage directory"
 STORAGE_DIR_DESC: "La ruta donde Pdx-Unlimiter guarda todos las partidas importadas.\nEsto es completamente independiente de las rutas de partidas guardadas de tus juegos de Paradox"
 STORAGE_DIR_DIALOG_TITLE: "Confirmar movimiento de almacenamiento"
 STORAGE_DIR_DIALOG_TEXT: "Estás intentando mover tu almacenamiento de partidas guardadas de $FROM$\na $TO$.\nEsto moverá todos los archivos de partidas guardadas y puede tardar un tiempo."
 STORAGE_DIR_SAVEGAME_WARNING_TITLE: "Ruta de almacenamiento interno inválida"
 STORAGE_DIR_SAVEGAME_WARNING_TEXT: "La ruta seleccionada para el almacenamiento interno de Pdx-Unlimiter parece ser la ruta de partidas guardadas de un juego.\Ten en cuenta que el almacenamiento interno de Pdx-Unlimiter no esta relacionado con las partidas guardadas de los juegos de Paradox.\n"
 STORAGE_DIR_RESET_TITLE: "Ruta de almacenamiento no existe"
 STORAGE_DIR_RESET_TEXT: "La ruta de almacenamiento $PATH$ no existe o ya no es válida\n¿Quieres restablecerla a la ruta predeterminada?"
 STORAGE_DIR_INVALID_TITLE: "Ruta de almacenamiento no existe"
 STORAGE_DIR_INVALID_TEXT: "La ruta de almacenamiento $PATH$ no existe o ya no es válida."
 EU4SE: "OsaSaveEditor"
 ENABLE_EU4SE: "Habilitar OsaSaveEditor"
 ENABLE_EU4SE_DESC: "Especifica si habilitar el OsaSaveEditor.\n\nSi habilitas esto, el OsaSaveEditor se descargará e instalará la próxima vez que inicies Pdx-Unlimiter."
 MISC: "Misceláneo"
 FONT_SIZE: "Tamaño de fuente"
 FONT_SIZE_DESC: "El tamaño de fuente dentro de la aplicación.\n\nSi tienes una alta resolución de pantalla, puedes aumentar esto para mejorar la legibilidad."
 ENABLE_AUTOUPDATE: "Habilitar actualización automática"
 ENABLE_AUTOUPDATE_DESC: "Especifica si actualizar automáticamente Pdx-Unlimiter y sus componentes al iniciarla."
 CONFIRM_DELETION: "Confirmar borrado"
 CONFIRM_DELETION_DESC: "Especifica si preguntar antes de borrar una campaña o partida guardada."
 START_STEAM: "Iniciar a través de Steam"
 START_STEAM_DESC: "Especifica si iniciar Steam al lanzar un juego a través de Pdx-Unlimiter.\n\nSi deshabilitas esto, Steam podría no registrar tus logros mientras juegas."
 DELETE_ON_IMPORT: "Eliminar original después de importar"
 DELETE_ON_IMPORT_DESC: "Especifica si eliminar partidas guardadas después de importarlas con éxito al almacenamiento de Pdx-Unlimiter."
 SKANDERBEG: "Skanderbeg.pm"
 SKANDERBEG_API_KEY: "API key"
 SKANDERBEG_API_KEY_DESC: "Tu clave API de Skanderbeg.pm.\n\nPuedes encontrar esto yendo a la página 'API' en Skanderbeg.pm."
 CONVERTERS: "Convertidores de Paradox"
 CK3_TO_EU4_DIR: "Convertidor de CK3 a EU4"
 CK3_TO_EU4_DIR_DESC: "La ruta al convertidor CK3ToEU4."
 VIC3_TO_HOI4_DIR: "Convertidor de VIC3 a HOI4"
 VIC3_TO_HOI4_DIR_DESC: "La ruta al convertidor Vic3ToHoi4."
 EU4_TO_VIC3_DIR: "Convertidor de EU4 a VIC3"
 EU4_TO_VIC3_DIR_DESC: "La ruta al convertidor Eu4ToVic3."
 IRONY_DIR: "Ruta de instalación"
 IRONY_DIR_DESC: "La ruta instalación de Irony."
 LAUNCH_IRONY: "Iniciar Irony"
 LAUNCH_IRONY_DESC: "Inicia Irony mod manager en vez de Paradox Launcher"
 TIMED_IMPORTS: "Importaciones programadas"
 TIMED_IMPORTS_DESC: "Habilita la importación automática de la última partida guardada después de un cierto tiempo mientras juegas."
 TIMED_IMPORTS_INTERVAL: "Minutos entre importaciones"
 TIMED_IMPORTS_INTERVAL_DESC: "El tiempo en minutos entre importaciones automáticas."
 THIRD_PARTY_ERROR: "El soporte de $APP$ ha sido deshabilitado.\nSi crees que la instalación es válida,\npor favor verifica si la ruta de instalación es correcta."
 PLAY_SOUND_ON_BACKGROUND_IMPORT: "Reproducir sonido en importación en segundo plano"
 PLAY_SOUND_ON_BACKGROUND_IMPORT_DESC: "Reproduce un sonido cuando se importa una partida en segundo plano mientras el juego está abierto."
 XBOX_UNAVAILABLE: "Este juego no tiene una distribución de Windows Store."
 XBOX_DIST_BUTTON: "Seleccionar distribución de Windows Store.\nEsto solo funciona si tienes una versión de Windows Store del juego instalada."
 CLEAR_DIST_BUTTON: "Limpiar la distribución de juego seleccionada."
 BROWSE_DIST_BUTTON: "Localizar la ruta de instalación manualmente."
 IMPORT_ON_NORMAL_GAME_EXIT: "Importar al salir del juego"
 IMPORT_ON_NORMAL_GAME_EXIT_DESC: "Importa automáticamente la última partida guardada al salir del juego normalmente, es decir, cuando no se usan funciones de savescum."