l_portuguese:
 SETTINGS: "Configurações"
 INTERFACE:  "Interface"
 GENERAL: "Gera"
 IMPORTS: "Importações"
 IRONY: "Gerenciador de mods Irony"
 USE_GAME_LANGUAGE: "Usar idioma do jogo"
 MAX_TOOLTIP_SIZE: "Largura máxima da dica de ferramenta"
 MAX_TOOLTIP_SIZE_DESC: "A largura máxima das dicas de ferramentas de visualização de nós em pixels."
 USE_GAME_LANGUAGE_DESC: "Sempre use o idioma do jogo selecionado no momento.\nSe isso estiver ativado, a configuração de idioma personalizado abaixo não será usada. Observe que as traduções estão incompletas!"
 LANGUAGE: "Idioma"
 LANGUAGE_DESC: "O idioma da interface personalizada a ser usado.\nSó será aplicado se a configuração 'Usar idioma do jogo' for falsa."
 SELECT_DIR: "Selecione o diretório $DIR$"
 CHOICE_VALUE_ERROR: "O valor $VAL$ é inválido. Redefinindo-o para um valor padrão."
 GAME_DIRS: "Instalações de jogos"
 GAME_DIR_ERROR: "Ocorreu um erro ao carregar a instalação de $GAME$"
 GAME_DIR_ERROR_MSG: "O suporte a $GAME$ foi desativado. Se você acredita que sua instalação é válida, verifique se o diretório de instalação foi definido corretamente."
 GAME_DIR: "Instalação do $GAME$"
 GAME_DIR_DESC: "O diretório de instalação $GAME$.\n\nObserve que esse deve ser o diretório de instalação que contém o executável do jogo e os ativos.\nNÃO o diretório de usuário que contém seus jogos salvos e mods."
 STORAGE_DIR: "Diretório de armazenamento"
 STORAGE_DIR_DESC: "O diretório em que o Pdx-Unlimiter armazena todos os jogos salvos importados.\nObserve que isso é completamente independente dos diretórios de jogos salvos de seus jogos da Paradox!"
 STORAGE_DIR_DIALOG_TITLE: "Confirme a mudança de armazenamento"
 STORAGE_DIR_DIALOG_TEXT: "Você está tentando mover o armazenamento de jogos salvos de $FROM$\npara $TO$.\nIsso moverá todos os arquivos de jogos salvos e pode demorar um pouco."
 STORAGE_DIR_SAVEGAME_WARNING_TITLE: "Local de armazenamento interno inválido"
 STORAGE_DIR_SAVEGAME_WARNING_TEXT: "O diretório que você selecionou como local de armazenamento interno do Pdx-Unlimiter parece um diretório de jogo salvo de um jogo.\nPor favor, observe que o armazenamento interno do Pdx-Unlimiter não está relacionado aos diretórios de savegame dos jogos da Paradox.\n"
 STORAGE_DIR_RESET_TITLE: "O diretório de armazenamento não existe"
 STORAGE_DIR_RESET_TEXT: "O diretório de armazenamento $PATH$ não existe ou é inválido\nDeseja redefini-lo para o diretório padrão?"
 STORAGE_DIR_INVALID_TITLE: "O diretório de armazenamento não existe"
 STORAGE_DIR_INVALID_TEXT: "O diretório de armazenamento $PATH$ não existe ou não é válido."
 EU4SE: "OsaSaveEditor"
 ENABLE_EU4SE: "Habilitar o OsaSaveEditor"
 ENABLE_EU4SE_DESC: "Especifica se o OsaSaveEditor deve ser ativado.\n\nSe você ativar essa opção, o OsaSaveEditor será baixado e instalado na próxima vez que você iniciar o Pdx-Unlimiter."
 MISC: "Diversos"
 FONT_SIZE: "Tamanho da fonte"
 FONT_SIZE_DESC: "O tamanho da fonte no aplicativo.\n\nSe você tiver uma resolução de tela alta, poderá aumentá-la para aumentar a legibilidade."
 ENABLE_AUTOUPDATE: "Habilitar atualização automática"
 ENABLE_AUTOUPDATE_DESC: "Especifica se deve atualizar automaticamente o Pdx-Unlimiter e seus componentes ao iniciá-lo."
 CONFIRM_DELETION: "Confirmar remoção"
 CONFIRM_DELETION_DESC: "Especifica se deve solicitar confirmação ao excluir uma campanha ou jogo salvo."
 START_STEAM: "Iniciar pelo Steam"
 START_STEAM_DESC: "Especifica se o Steam deve ser iniciado ao iniciar um jogo por meio do Pdx-Unlimiter.\n\nSe você desativar essa opção, o Steam poderá não registrar suas conquistas durante o jogo."
 DELETE_ON_IMPORT: "Excluir o original após a importação"
 DELETE_ON_IMPORT_DESC: "Especifica se os jogos salvos devem ser excluídos após a importação bem-sucedida para o armazenamento do Pdx-Unlimiter."
 SKANDERBEG: "Skanderbeg.pm"
 SKANDERBEG_API_KEY: "Chave de API"
 SKANDERBEG_API_KEY_DESC: "Sua chave de API do Skanderbeg.pm.\n\nVocê pode encontrá-la acessando a página 'API' no Skanderbeg.pm."
 CONVERTERS: "Conversores Paradox"
 CK3_TO_EU4_DIR: "Conversor de CK3 para EU4"
 CK3_TO_EU4_DIR_DESC: "O caminho para o conversor CK3ToEU4."
 VIC3_TO_HOI4_DIR: "Conversor de VIC3 para HOI4"
 VIC3_TO_HOI4_DIR_DESC: "O caminho para o conversor Vic3ToHoi4."
 EU4_TO_VIC3_DIR: "Conversor de EU4 para VIC3"
 EU4_TO_VIC3_DIR_DESC: "O caminho para o conversor Eu4ToVic3."
 IRONY_DIR: "Local de instalação"
 IRONY_DIR_DESC: "O local de sua instalação do Irony."
 LAUNCH_IRONY: "Iniciar Irony"
 LAUNCH_IRONY_DESC: "Inicia o gerenciador de mods Irony em vez do Paradox Launcher"
 TIMED_IMPORTS: "Importações por tempo ativadas"
 TIMED_IMPORTS_DESC: "Permite importar automaticamente o jogo salvo mais recente após um determinado período de tempo durante o jogo."
 TIMED_IMPORTS_INTERVAL: "Minutos entre importações"
 TIMED_IMPORTS_INTERVAL_DESC: "O intervalo entre as importações automáticas em minutos."
 THIRD_PARTY_ERROR: "O suporte a $APP$ foi desativado.\nSe você acredita que a instalação é válida,\npor favor, verifique se o diretório de instalação foi definido corretamente."
 PLAY_SOUND_ON_BACKGROUND_IMPORT: "Reproduzir som na importação em segundo plano"
 PLAY_SOUND_ON_BACKGROUND_IMPORT_DESC: "Emitir um bipe ao importar um jogo salvo enquanto um jogo estiver aberto e o Pdx-Unlimiter estiver em execução em segundo plano."
 XBOX_UNAVAILABLE: "Este jogo não tem uma distribuição na Windows Store."
 XBOX_DIST_BUTTON: "Selecione a distribuição da Windows Store.\nIsso só funciona se você tiver uma versão do jogo instalada na Windows Store."
 CLEAR_DIST_BUTTON: "Limpar a distribuição de jogos atualmente selecionada."
 BROWSE_DIST_BUTTON: "Localize o diretório de instalação manualmente."
 IMPORT_ON_NORMAL_GAME_EXIT: "Importar ao sair do jogo"
 IMPORT_ON_NORMAL_GAME_EXIT_DESC: "Importe automaticamente o jogo salvo mais recente ao sair do jogo normalmente, ou seja, quando não estiver usando nenhum recurso de salvamento."